services:
    # There is no point of using autowire here as we have a lot of services without classes and with parent definition.

    # Converter
    training_user_naming.importexport.data_converter.user_naming_type:
        parent: oro_importexport.data_converter.configurable

    training_user_naming.importexport.data_converter.template_fixture.user_naming_type:
        parent: oro_importexport.data_converter.template_fixture.configurable

    # Strategy
    training_user_naming.importexport.strategy.user_naming_type.add_or_replace:
        parent: oro_importexport.strategy.configurable_add_or_replace

    # Export processor
    training_user_naming.importexport.processor.export.user_naming_type:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, ['@training_user_naming.importexport.data_converter.user_naming_type']]
        tags:
            -
                name: oro_importexport.processor
                type: export
                entity: 'Training\Bundle\UserNamingBundle\Entity\UserNamingType'
                alias: training_user_naming_type

    training_user_naming.importexport.processor.export_template.user_naming_type:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, ['@training_user_naming.importexport.data_converter.template_fixture.user_naming_type']]
        tags:
            -
                name: oro_importexport.processor
                type: export_template
                entity: 'Training\Bundle\UserNamingBundle\Entity\UserNamingType'
                alias: training_user_naming_type

    # Import processor
    training_user_naming.importexport.processor.import.user_naming_type:
        parent: oro_importexport.processor.import_abstract
        calls:
             - [setDataConverter, ['@training_user_naming.importexport.data_converter.user_naming_type']]
             - [setStrategy, ['@training_user_naming.importexport.strategy.user_naming_type.add_or_replace']]
        tags:
            -
                name: oro_importexport.processor
                type: import
                entity: 'Training\Bundle\UserNamingBundle\Entity\UserNamingType'
                alias: training_user_naming_type_add_or_replace
            -
                name: oro_importexport.processor
                type: import_validation
                entity: 'Training\Bundle\UserNamingBundle\Entity\UserNamingType'
                alias: training_user_naming_type_add_or_replace

    # Template fixture
    # Autowiring + _instanceof configuration could be used here
    training_user_naming.importexport.template_fixture.user_naming_type:
        class: Training\Bundle\UserNamingBundle\ImportExport\TemplateFixture\UserNamingTypeFixture
        tags:
            - { name: oro_importexport.template_fixture }

    # Configuration
    # Autowiring could be used here
    training_user_naming.importexport.configuration_provider.training_user_naming:
        class: Training\Bundle\UserNamingBundle\ImportExport\Configuration\UserNamingImportExportConfigurationProvider
        tags:
            - { name: oro_importexport.configuration, alias: training_user_naming }
