services:
    _defaults:
        autowire: true

    Training\Bundle\UserNamingBundle\Api\Processor\Get\NameExampleGetProcessor:
        tags:
            -
                name: oro.api.processor
                action: get
                group: finalize
                class: 'Training\Bundle\UserNamingBundle\Entity\UserNamingType'
                priority: -25

    Training\Bundle\UserNamingBundle\Api\Processor\GetList\NameExampleGetListProcessor:
        tags:
            -
                name: oro.api.processor
                action: get_list
                group: finalize
                class: 'Training\Bundle\UserNamingBundle\Entity\UserNamingType'
                priority: -25
